# Generated by Django 5.1.1 on 2024-09-18 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry_entities', '0002_alter_organization_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='company_registration_number',
            field=models.CharField(blank=True, default='SEM CADASTRO', max_length=20, null=True, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='company_registration_number',
            field=models.CharField(blank=True, default='SEM CADASTRO', max_length=20, null=True, verbose_name='CNPJ'),
        ),
    ]
