# Generated by Django 5.1.1 on 2024-09-26 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "registry_entities",
            "0003_alter_division_company_registration_number_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="division",
            options={"ordering": ["created_at"]},
        ),
    ]
